TournamentStart: "&bA partida de SkyWars irá começar em %time% segundos"
Prefix: "&6&lSKYWARS &f"
TournamentTimeChanged: "&eO temporizador de partida foi encurtado por ter muitos jogadores!"
TournamentStarted: "&bA partida foi iniciada!"
PlayerJoinedMatch: "&e%player% entrou na partida!"
PlayerLeaveServer: "&e%player% saiu da partida."
PlayerLeaveServerDeath: "&c%player% saiu e foi eliminado da partida"
PlayerKilledMessage: "&cVocê foi morto no skywars"
PlayerKilledBroadcast: "&b%player% foi morto por %killer%!"
PlayersLeft: "&b%left% Jogadores restantes"
Searching: "&bSearching for the next two Players for Battle!"
CommandBlockedInBattle: "&eEsse comando está bloqueado em partida!"
CommandBlocked: "&eEscreva /sw leave para sair do skywars"
EventWinner: "&a%player% venceu a partida!"
Fight: "&6NEXT FIGHT: &e%player1% VS %player2%"
FightAgainst: "&aYou will fight against %player%"
SwordName: "&aSword"
Joined: "&aVocê entrou no lobby do Skywars."
JoinTitle: "&aBem vindo"
JoinSubTitle: "&fAo skywars"
TournamentLeave: "Você saiu do skywars!"
TournamentStartGlobal: "&eUma partida de skywars irá começar em %time% segundos. Clique aqui para entrar nela."
ClickToJoin: "&bClique aqui para entrar na partida!"
MatchStart: "A partida iniciou! Que vença o melhor!"
SendIPAddressData: true